name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.13
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "cs-crosshair-finder"
          heroku_email: "emmanuelvlad@gmail.com"
          buildpack: "https://github.com/HashNuke/heroku-buildpack-elixir.git"
        env:
          FACEIT_API_KEY: ${{secrets.FACEIT_API_KEY}}
